### ISSUE TITLE
Missing `systemd.install.xml` documentation file

### ISSUE THREAD

**Issue by ValdezFOmar** [psacawa/systemd-language-server#2]
When I hover over an attribute under an `[Install]` section I get an error because the server is trying to open a file called `systemd.install.xml` that doesn´t exist.

Stacktrace:

```pytb
Failed to handle request 15 textDocument/hover HoverParams(text_document=TextDocumentIdentifier(uri='file:///home/omar/.config/systemd/user/tldr-cache.timer'), position=10:5, work_done_token=None)
Traceback (most recent call last):
  File "/home/omar/.local/pipx/venvs/systemd-language-server/lib/python3.11/site-packages/pygls/protocol/json_rpc.py", line 266, in _handle_request
    self._execute_request(msg_id, handler, params)
  File "/home/omar/.local/pipx/venvs/systemd-language-server/lib/python3.11/site-packages/pygls/protocol/json_rpc.py", line 188, in _execute_request
    self._send_response(msg_id, handler(params))
                                ^^^^^^^^^^^^^^^
  File "/home/omar/.local/pipx/venvs/systemd-language-server/lib/python3.11/site-packages/systemd_language_server/server.py", line 131, in textDocument_hover
    contents = get_documentation_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omar/.local/pipx/venvs/systemd-language-server/lib/python3.11/site-packages/systemd_language_server/unit.py", line 135, in get_documentation_content
    stream = StringIO(open(filepath).read())
                      ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/omar/.local/pipx/venvs/systemd-language-server/lib/python3.11/site-packages/systemd_language_server/assets/systemd.install.xml'
```

The file I was editing:

```service
[Unit]
Description=Refresh Pacman mirrorlist weekly with Reflector.

[Timer]
OnCalendar=weekly
Persistent=true
AccuracySec=1us
RandomizedDelaySec=12h

[Install]
WantedBy=timers.target
```

**Comment by psacawa** [comment]
Thanks for catching this, it's solved in #3.
